### ISSUE TITLE
log high score

### ISSUE THREAD

**Issue by dhebbeker** [dhebbeker/memorex-android#4]
Log the highest score. This feature can be designed extensively. This issue does request only the most basic mechanism.

**Comment by TinkaGrosse** [comment]
Totally seconded!
I would also welcome if you could unlock different Memorex leves for yourself: superbrain. memory star ...

**Comment by dhebbeker** [comment]
@TinkaGrosse 
> I would also welcome if you could unlock different Memorex leves for yourself

I did not quite get it. Do you mean s.th. like badges? That would be a good idea.

**Comment by dhebbeker** [comment]
This feature is included in [release 1.1.0][1]. <img src="https://user-images.githubusercontent.com/1594340/37565869-69783cbc-2ab1-11e8-8ba4-1dec726e93c4.png" width=200>


[1]: https://github.com/dhebbeker/memorex-android/releases/tag/v1.1.0
